name: Test application

on:
  push:
    branches: [ qa ]
  pull_request:
    branches: [ qa ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CHANGE_MINIKUBE_NONE_USER: true
    defaults:
      run:
        working-directory: finish

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: unset _JAVA_OPTIONS
    - name: Set up Minikube
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
        chmod +x kubectl
        sudo ln -s $(pwd)/kubectl /usr/local/bin/kubectl
        wget https://github.com/kubernetes/minikube/releases/download/v0.28.2/minikube-linux-amd64 -q -O minikube
        chmod +x minikube
    - name: Install Conn Track 
      run: |
        sudo apt-get update -y
        sudo apt-get install -y conntrack
    - name: Start Minikube
      run: sudo minikube start --vm-driver=none --bootstrapper=kubeadm
    - name: Run tests
      run: sudo ../scripts/travisTest.sh
    - name: Post tests
      if: always()
      run: sudo docker images
